---
- name: Turning off authentification with password
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: PasswordAuthentication no
    owner: root
    group: root
    mode: '0644'
