---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-server
  labels:
    app: wp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: wp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wp
    spec:
      containers:
        - name: wp-server
          image: wordpress:latest
          ports:
          - containerPort: 80
            name: http-web-svc
      #     volumeMounts:
      #       - name: wordpress-data
      #         mountPath: /var/www
      #     env:
      #       - name: WORDPRESS_DB_HOST
      #         value: 35.195.154.212
      #       - name: WORDPRESS_DB_PASSWORD
      #         value: wppass 
      #       - name: WORDPRESS_DB_USER
      #         value: wpuser
      #       - name: WORDPRESS_DB_NAME
      #         value: wpdb
      # volumes:
      #   - name: wordpress-data
      #     persistentVolumeClaim:
      #       claimName: wordpress-volume

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wp-server
#   labels:
#     app: wp
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: wp
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: wp
#     spec:
#       containers:
#       - name: wp-server
#         image: wordpress:latest
#         ports:
#         - containerPort: 80
#           name: http-web-svc

      #   volumeMounts:
      #   - name: wp
      #     mountPath: /var/www/html/wp-config.php
      # volumes:
      #   - name: wp
      #     hostPath:
      #       path: /root
      #       type: FileOrCreate  
          # env:
          # - name: WORDPRESS_DB_HOST
          #   value: 35.195.154.212
          # - name: WORDPRESS_DB_USER
          #   value: wpuser
          # - name: WORDPRESS_DB_PASSWORD
          #   value: wppass
          # - name: WORDPRESS_DB_NAME
          #   value: wpdb


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wp
#   labels:
#     app: wp
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: wp
#   template:
#    metadata:
#     labels:
#         app: wp
#    spec:
#      containers:
#      - name: wp
#        image: wordpress
#        ports:
#        - containerPort: 80
#          name: http-web-svc
#        env:
#        - name: WORDPRESS_DB_HOST
#          value: 35.195.154.212
#        - name: WORDPRESS_DB_USER
#          value: wpuser
#        - name: WORDPRESS_DB_PASSWORD
#          value: wppass
#        - name: WORDPRESS_DB_NAME
#          value: wpdb
---

apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
  selector:
    app.kubernetes.io/name: wp
  ports:
  - name: wpp
    protocol: TCP
    port: 80
    targetPort: http-web-svc
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
  - hosts:
    - finaltaskgl.v6.rocks
    secretName: quickstart-example-tls
  rules:
  - host: finaltaskgl.v6.rocks
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wp-service
            port:
              number: 80