
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wp
#   labels:
#     app: wp
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: wp
#   template:
#    metadata:
#     labels:
#         app: wp
#    spec:
#     containers:
#     - name: wp
#       image: nginx
#         env:
#         - name: WORDPRESS_DB_HOST
#           value: 35.195.154.212
#         - name: WORDPRESS_DB_USER
#           value: wpuser
#         - name: WORDPRESS_DB_PASSWORD
#           value: wppass
#         - name: WORDPRESS_DB_NAME
#           value: wpdb
#         ports:
#         - containerPort: 80
#           name: http-web-svc

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: wordpress
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: wordpress
#   template:
#     metadata:
#       labels:
#         app: wordpress
#     spec:
#       volumes:
#         - name: wordpress
#           hostPath:
#             path: /srv/k8s-volumes/wordpress
#       containers:
#       - name: wordpress
#         image: wordpress:5.3.0
#         ports:
#         - containerPort: 80
#         env:
#         - name: WORDPRESS_DB_HOST
#           value: mysql:3306
#         - name: WORDPRESS_DB_USER
#           value: wordpress
#         - name: WORDPRESS_DB_PASSWORD
#           value: password
#         - name: WORDPRESS_DB_NAME
#           value: wordpress
#         - name: WORDPRESS_CONFIG_EXTRA
#           value: >
#             define('FS_METHOD','direct');
#         volumeMounts:
#           - name: wordpress
#             mountPath: /var/www/html/wp-content
          
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-server
#   labels:
#     app: nginx
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: nginx-server
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: nginx-server
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:stable
#         ports:
#         - containerPort: 80
#           name: http-web-svc
